from grafosEA import Vertice, Aresta, GrafoEstrutura
def grafoExemplo():
  grafo = GrafoEstrutura()
  u = Vertice('u')
  y = Vertice('y')
  v = Vertice('v')
  x = Vertice('x')
  w = Vertice('w')

  grafo.adicionarVertices([u, y, v, x, w])

  grafo.criarAresta(u, y)
  grafo.criarAresta(u, v)
  grafo.criarAresta(y, v)
  grafo.criarAresta(y, v)
  grafo.criarAresta(y, w)
  grafo.criarAresta(v, w)
  grafo.criarAresta(x, w)
  grafo.criarAresta(x, y)

  a = Aresta(u,v)
  b = Aresta(v,w)
  c = Aresta(w,x)
  d = Aresta(x,y)
  e = Aresta(u,y)
  f = Aresta(y,v)
  g = Aresta(v,y)
  h = Aresta(y,w)

  print("GRAFO EXEMPLO")
  grafo.imprimirGrafo()
  print("A) SUBGRAFO PRÓPIO")
  grafo.gerarSubgrafo([u,y,v], [f,e])
  print("B) SUBGRAFO GERADOR")
  grafo.gerarSubgrafo([u,y,v,x,w], [])
  print("C) SUBGRAFO INDUZIDO")
  grafo.gerarInduzido([y,v,x,u])
  print("D) SUBTRAÇÃO DE VÉRTICES")
  grafo.subtrairVertices([u,w])
  print("E) SUBGRAFO ARESTA INDUZIDO")
  grafo.gerarArestaInduzido([a,c,e,g])
  print("F) SUBTRAÇÃO DE ARESTAS")
  grafo.subtrairArestas([a,b,f])

grafoExemplo()
